// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://ruubwpgemhyzsrbqspnj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ1dWJ3cGdlbWh5enNyYnFzcG5qIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk2MjkwNDUsImV4cCI6MjA3NTIwNTA0NX0.b9uxQ_iu-DmMZKrbsakWW9Y6trastDhObMHVWBq3udU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);